# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Docker build and push to Artifact Registry
      run: |
        gcloud auth list
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://europe-west1-docker.pkg.dev
        docker build -t europe-west1-docker.pkg.dev/oredata-ops-demo/github-actions-test/python_flask:${{ github.sha }} .
        docker push europe-west1-docker.pkg.dev/oredata-ops-demo/github-actions-test/python_flask:${{ github.sha }}
